apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wiki-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-mysql
  template:
    metadata:
      labels:
        app: wiki-mysql
    spec:
      containers:
        - name: mysql
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: wiki-db-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-mysql-svc
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: wiki-mysql


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-deployment
  labels:
    app: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: mediawiki
          image: mediawiki:1.38.1
          ports:
            - containerPort: 80
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-data-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
  selector:
    app: wiki
